# Database
database:
    name: insert_here
    user: insert_here
    password: insert_here
    port: insert_here
    host: insert_here
    charset: insert_here

# Yelp
yelp:
    api:
        v1.0:
            ywsid: insert_here
        v2.0:
            consumer_key: insert_here
            consumer_secret: insert_here
            token: insert_here
            token_secret: insert_here